title: KhaosShield's Blog
description: "Writeups, Reviews, Walkthroughs & Resources from an aspiring Ethical Hacker & Penetration Tester."
author:
  name: "KhaosShield"
  email: "khaosshield@protonmail.com"
  url: "https://github.com/KhaosShield"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "KhaosShield"
year : "2020"
